[project]
name = "job-spider"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "fastapi>=0.115.12",
    "playwright>=1.52.0",
    "uvicorn[standard]>=0.34.2",
]
